language: scala

scala:
  - 2.11.7

services:
  - cassandra

before_script:
  -  "/usr/local/cassandra/bin/cqlsh -e \"CREATE KEYSPACE IF NOT EXISTS test WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };\""
